name: Lint Rust

permissions:
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint-rust.yml'
      - 'src-tauri/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint-rust.yml'
      - 'src-tauri/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-rust:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Mock Files
        run: |
          mkdir -p elk/.output/public

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=Cargo.toml --all -- --check